#!/usr/bin/env python3
"""
FastChat Setup Helper

Helps detect, configure, and test FastChat provider connectivity.
Provides setup guidance and troubleshooting for FastChat integration.
"""

import os
import sys
import requests
import subprocess
import time
from typing import Dict, List, Optional, Tuple
from pathlib import Path


class FastChatSetupHelper:
    """Helper for FastChat provider setup and configuration."""
    
    def __init__(self):
        self.default_ports = [8000, 8001, 7860, 5000, 5001]
        self.health_endpoints = [
            "/v1/models",
            "/models", 
            "/health",
            "/"
        ]
    
    def check_fastchat_installation(self) -> Tuple[bool, str]:
        """Check if FastChat is installed."""
        try:
            import fastchat
            version = getattr(fastchat, '__version__', 'unknown')
            return True, f"FastChat v{version} found"
        except ImportError:
            return False, "FastChat not installed"
    
    def check_fastchat_running(self, host: str = "127.0.0.1", ports: List[int] = None) -> Tuple[bool, str, str]:
        """Check if FastChat server is running."""
        if ports is None:
            ports = self.default_ports
        
        for port in ports:
            base_url = f"http://{host}:{port}"
            
            for endpoint in self.health_endpoints:
                url = f"{base_url}{endpoint}"
                
                try:
                    response = requests.get(url, timeout=3)
                    if response.status_code == 200:
                        return True, f"FastChat running at {base_url}", base_url
                except requests.exceptions.RequestException:
                    continue
        
        return False, "FastChat server not found", ""
    
    def test_fastchat_api(self, base_url: str, api_key: str = "dummy-key") -> Tuple[bool, str]:
        """Test FastChat API functionality."""
        try:
            # Test models endpoint
            models_url = f"{base_url}/v1/models"
            headers = {"Authorization": f"Bearer {api_key}"}
            
            response = requests.get(models_url, headers=headers, timeout=10)
            
            if response.status_code == 200:
                models_data = response.json()
                models = models_data.get("data", [])
                
                if models:
                    model_names = [model.get("id", "unknown") for model in models[:3]]
                    return True, f"API working. Available models: {', '.join(model_names)}"
                else:
                    return False, "API responds but no models found"
            else:
                return False, f"API test failed with status {response.status_code}"
                
        except Exception as e:
            return False, f"API test error: {str(e)}"
    
    def generate_env_config(self, base_url: str, api_key: str = "dummy-key") -> str:
        """Generate environment configuration for FastChat."""
        config = f"""# FastChat Provider Configuration
# Generated by FastChat Setup Helper

# Provider selection
AI_PROVIDER=openai_compatible

# FastChat API endpoint
AI_BASE_URL={base_url}

# API key (FastChat typically accepts dummy keys)
AI_API_KEY={api_key}

# Model selection (use a model available in your FastChat instance)
AI_MODEL=vicuna-7b-v1.5

# Optional: Cache settings
AI_CACHE_ENABLED=true
AI_CACHE_TTL_S=3600
"""
        return config
    
    def generate_setup_commands(self, base_url: str) -> List[str]:
        """Generate setup commands for different shells."""
        return [
            f"# For bash/zsh:",
            f"export AI_PROVIDER=openai_compatible",
            f"export AI_BASE_URL={base_url}",
            f"export AI_API_KEY=dummy-key",
            f"export AI_MODEL=vicuna-7b-v1.5",
            "",
            f"# For PowerShell:",
            f"$env:AI_PROVIDER='openai_compatible'",
            f"$env:AI_BASE_URL='{base_url}'",
            f"$env:AI_API_KEY='dummy-key'",
            f"$env:AI_MODEL='vicuna-7b-v1.5'"
        ]
    
    def start_fastchat_server(self, model_path: str = None, host: str = "127.0.0.1", port: int = 8000) -> bool:
        """Provide guidance for starting FastChat server."""
        print("🚀 FastChat Server Setup Guidance")
        print("=" * 50)
        
        if model_path:
            print(f"Model path: {model_path}")
        else:
            print("Model path: Not specified (using default)")
        
        print(f"\nBasic startup command:")
        print(f"python -m fastchat.serve.cli --model-path {model_path or '/path/to/your/model'} --host {host} --port {port}")
        
        print(f"\nAdvanced startup with API server:")
        print(f"# Terminal 1 - Start controller:")
        print(f"python -m fastchat.serve.controller")
        print(f"\n# Terminal 2 - Start model worker:")
        print(f"python -m fastchat.serve.cli --model-path {model_path or '/path/to/your/model'}")
        print(f"\n# Terminal 3 - Start API server:")
        print(f"python -m fastchat.serve.openai_api_server --host {host} --port {port}")
        
        print(f"\nFor more options, see FastChat documentation:")
        print(f"https://github.com/lm-sys/FastChat")
        
        return True
    
    def troubleshoot_connection(self, base_url: str) -> List[str]:
        """Provide troubleshooting steps for connection issues."""
        issues = []
        
        # Check basic connectivity
        try:
            response = requests.get(base_url, timeout=5)
            if response.status_code != 200:
                issues.append(f"Server responds with status {response.status_code} (expected 200)")
        except requests.exceptions.ConnectionError:
            issues.append("Cannot connect to server - check if FastChat is running")
        except requests.exceptions.Timeout:
            issues.append("Connection timeout - server may be slow to respond")
        
        # Check API endpoint
        try:
            models_url = f"{base_url}/v1/models"
            response = requests.get(models_url, timeout=5)
            if response.status_code == 404:
                issues.append("OpenAI-compatible API endpoint not found - check server configuration")
            elif response.status_code == 401:
                issues.append("Authentication required - check API key")
        except:
            issues.append("Cannot reach API endpoint - verify FastChat API server is running")
        
        # Add general advice
        issues.extend([
            "Make sure FastChat API server is running (not just the model worker)",
            "Check that the correct port is being used",
            "Verify firewall settings aren't blocking the connection",
            "Ensure FastChat is properly installed and updated"
        ])
        
        return issues
    
    def run_diagnostic(self) -> bool:
        """Run complete FastChat diagnostic."""
        print("🔍 FastChat Diagnostic Tool")
        print("=" * 40)
        
        # Check installation
        print("\n1. Checking FastChat installation...")
        installed, info = self.check_fastchat_installation()
        if installed:
            print(f"✅ {info}")
        else:
            print(f"❌ {info}")
            print("Install FastChat with: pip install fschat")
            return False
        
        # Check running server
        print("\n2. Checking for running FastChat server...")
        running, info, url = self.check_fastchat_running()
        if running:
            print(f"✅ {info}")
            
            # Test API
            print("\n3. Testing FastChat API...")
            api_works, api_info = self.test_fastchat_api(url)
            if api_works:
                print(f"✅ {api_info}")
                
                # Generate configuration
                print(f"\n4. Configuration for AI Utilities:")
                config = self.generate_env_config(url)
                print(config)
                
                return True
            else:
                print(f"❌ {api_info}")
                print("\nTroubleshooting suggestions:")
                for issue in self.troubleshoot_connection(url):
                    print(f"• {issue}")
                return False
        else:
            print(f"❌ {info}")
            print("\nTo start FastChat server:")
            self.start_fastchat_server()
            return False
    
    def interactive_setup(self) -> bool:
        """Interactive setup wizard."""
        print("🧙 FastChat Interactive Setup")
        print("=" * 35)
        
        # Check installation first
        installed, info = self.check_fastchat_installation()
        if not installed:
            print(f"❌ {info}")
            install = input("Install FastChat now? (y/n): ").lower().strip()
            if install == 'y':
                try:
                    subprocess.run([sys.executable, "-m", "pip", "install", "fschat"], check=True)
                    print("✅ FastChat installed successfully")
                except subprocess.CalledProcessError:
                    print("❌ Failed to install FastChat")
                    return False
            else:
                print("Please install FastChat manually: pip install fschat")
                return False
        
        # Find running server
        print("\n🔍 Looking for FastChat server...")
        running, info, url = self.check_fastchat_running()
        
        if not running:
            print("❌ No running FastChat server found")
            print("\nOptions:")
            print("1. Start FastChat server (requires model)")
            print("2. Enter server URL manually")
            print("3. Exit")
            
            choice = input("Choose option (1/2/3): ").strip()
            
            if choice == "1":
                model_path = input("Enter model path (or press Enter for default): ").strip()
                self.start_fastchat_server(model_path)
                input("\nPress Enter after starting FastChat server...")
                
                # Check again
                running, info, url = self.check_fastchat_running()
                if not running:
                    print("❌ Still cannot find FastChat server")
                    return False
                    
            elif choice == "2":
                url = input("Enter FastChat server URL (e.g., http://127.0.0.1:8000): ").strip()
                if not url.startswith('http'):
                    url = f"http://{url}"
                    
            elif choice == "3":
                return False
            else:
                print("Invalid choice")
                return False
        
        # Test the connection
        print(f"\n🧪 Testing connection to {url}")
        api_works, api_info = self.test_fastchat_api(url)
        
        if api_works:
            print(f"✅ {api_info}")
            
            # Save configuration
            save_config = input("\nSave configuration to .env file? (y/n): ").lower().strip()
            if save_config == 'y':
                config = self.generate_env_config(url)
                env_file = Path(".env")
                
                if env_file.exists():
                    backup_content = env_file.read_text()
                    env_file.write_text(f"{backup_content}\n{config}")
                else:
                    env_file.write_text(config)
                
                print(f"✅ Configuration saved to {env_file}")
            
            print(f"\n🎉 FastChat setup complete!")
            print(f"You can now use AI Utilities with FastChat provider")
            return True
        else:
            print(f"❌ {api_info}")
            print("\nTroubleshooting:")
            for issue in self.troubleshoot_connection(url):
                print(f"• {issue}")
            return False


def main():
    """Main entry point for FastChat setup helper."""
    import argparse
    
    parser = argparse.ArgumentParser(description="FastChat setup and diagnostic tool")
    parser.add_argument("--diagnostic", action="store_true", 
                       help="Run diagnostic only")
    parser.add_argument("--interactive", action="store_true",
                       help="Run interactive setup wizard")
    parser.add_argument("--check", action="store_true",
                       help="Check if FastChat is running")
    parser.add_argument("--url", type=str,
                       help="Test specific FastChat URL")
    
    args = parser.parse_args()
    
    helper = FastChatSetupHelper()
    
    if args.interactive:
        success = helper.interactive_setup()
    elif args.diagnostic:
        success = helper.run_diagnostic()
    elif args.check:
        running, info, url = helper.check_fastchat_running()
        if running:
            print(f"✅ {info}")
            success = True
        else:
            print(f"❌ {info}")
            success = False
    elif args.url:
        api_works, api_info = helper.test_fastchat_api(args.url)
        if api_works:
            print(f"✅ {api_info}")
            success = True
        else:
            print(f"❌ {api_info}")
            success = False
    else:
        # Default: run diagnostic
        success = helper.run_diagnostic()
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()