#!/usr/bin/env python3
"""
Text-Generation-WebUI Setup Helper

Comprehensive setup and configuration tool for Text-Generation-WebUI provider.
Helps with installation, configuration, testing, and troubleshooting.
"""

import os
import sys
import requests
import subprocess
import json
from typing import Dict, List, Optional, Tuple
from pathlib import Path


class TextGenerationWebUISetupHelper:
    """Helper for Text-Generation-WebUI setup and configuration."""
    
    def __init__(self):
        self.default_ports = [7860, 5000, 5001, 5002, 8000, 8001]
        self.api_endpoints = [
            "/v1/models",
            "/api/v1/models",
            "/models",
            "/api/models"
        ]
        self.webui_port = 7860  # Default web interface port
    
    def check_webui_installation(self) -> Tuple[bool, str]:
        """Check if Text-Generation-WebUI is installed."""
        webui_paths = [
            "text-generation-webui",
            "webui",
            "Text-Generation-WebUI"
        ]
        
        for path in webui_paths:
            if Path(path).exists():
                # Check for key files
                key_files = ["server.py", "webui.py", "requirements.txt"]
                found_files = [f for f in key_files if (Path(path) / f).exists()]
                
                if found_files:
                    return True, f"Text-Generation-WebUI found at {path}/"
        
        return False, "Text-Generation-WebUI not found in current directory"
    
    def check_webui_running(self, host: str = "127.0.0.1", ports: List[int] = None) -> Tuple[bool, str, str]:
        """Check if Text-Generation-WebUI is running."""
        if ports is None:
            ports = self.default_ports
        
        for port in ports:
            base_url = f"http://{host}:{port}"
            
            # Check web interface first
            try:
                response = requests.get(base_url, timeout=3)
                if response.status_code == 200 and "text-generation-webui" in response.text.lower():
                    return True, f"WebUI running at {base_url}", base_url
            except:
                pass
            
            # Check API endpoints
            for endpoint in self.api_endpoints:
                url = f"{base_url}{endpoint}"
                
                try:
                    response = requests.get(url, timeout=3)
                    if response.status_code == 200:
                        return True, f"API running at {base_url}", base_url
                except:
                    continue
        
        return False, "Text-Generation-WebUI not found", ""
    
    def test_webui_api(self, base_url: str, api_key: str = "") -> Tuple[bool, str]:
        """Test Text-Generation-WebUI API functionality."""
        try:
            # Test different API endpoints
            endpoints_to_test = [
                f"{base_url}/v1/models",
                f"{base_url}/api/v1/models",
                f"{base_url}/models"
            ]
            
            headers = {}
            if api_key:
                headers["Authorization"] = f"Bearer {api_key}"
            
            models_found = []
            working_endpoint = None
            
            for endpoint in endpoints_to_test:
                try:
                    response = requests.get(endpoint, headers=headers, timeout=10)
                    
                    if response.status_code == 200:
                        data = response.json()
                        
                        # Handle different response formats
                        if isinstance(data, dict) and "data" in data:
                            models = data["data"]
                        elif isinstance(data, list):
                            models = data
                        else:
                            continue
                        
                        if models:
                            models_found = [model.get("id", model.get("model", "unknown")) for model in models[:3]]
                            working_endpoint = endpoint
                            break
                            
                except:
                    continue
            
            if models_found:
                return True, f"API working at {working_endpoint}. Models: {', '.join(models_found)}"
            else:
                return False, "API responds but no models found"
                
        except Exception as e:
            return False, f"API test error: {str(e)}"
    
    def generate_env_config(self, base_url: str, api_key: str = "") -> str:
        """Generate environment configuration for Text-Generation-WebUI."""
        config = f"""# Text-Generation-WebUI Provider Configuration
# Generated by Text-Generation-WebUI Setup Helper

# Provider selection
AI_PROVIDER=openai_compatible

# Text-Generation-WebUI API endpoint
AI_BASE_URL={base_url}/v1

# API key (usually not required for local WebUI)
AI_API_KEY={api_key or 'not-required'}

# Model selection (use a model loaded in WebUI)
AI_MODEL=local-model

# Optional: Cache settings
AI_CACHE_ENABLED=true
AI_CACHE_TTL_S=3600

# Optional: Request settings
AI_REQUEST_TIMEOUT=120
AI_MAX_RETRIES=3
"""
        return config
    
    def install_webui(self, install_path: str = "text-generation-webui") -> bool:
        """Provide installation guidance for Text-Generation-WebUI."""
        print("📦 Text-Generation-WebUI Installation Guide")
        print("=" * 50)
        
        print(f"\nRecommended installation method:")
        print(f"1. Clone the repository:")
        print(f"   git clone https://github.com/oobabooga/text-generation-webui.git")
        print(f"2. Navigate to the directory:")
        print(f"   cd text-generation-webui")
        print(f"3. Install dependencies:")
        print(f"   pip install -r requirements.txt")
        print(f"4. Run the web interface:")
        print(f"   python server.py --api")
        
        print(f"\nAlternative: One-command installation:")
        print(f"   bash <(wget -qO- https://raw.githubusercontent.com/oobabooga/text-generation-webui/main/install.sh)")
        
        print(f"\nFor detailed instructions, visit:")
        print(f"https://github.com/oobabooga/text-generation-webui")
        
        return True
    
    def start_webui_server(self, model_path: str = None, host: str = "127.0.0.1", port: int = 7860, api_port: int = 5000) -> bool:
        """Provide guidance for starting Text-Generation-WebUI server."""
        print("🚀 Text-Generation-WebUI Server Setup")
        print("=" * 45)
        
        print(f"\nBasic startup with API:")
        print(f"cd text-generation-webui")
        print(f"python server.py --api --listen --api-port {api_port}")
        
        if model_path:
            print(f"\nWith specific model:")
            print(f"python server.py --api --listen --api-port {api_port} --model {model_path}")
        
        print(f"\nAdvanced options:")
        print(f"python server.py --api --listen --api-port {api_port} --chat --notebook")
        
        print(f"\nCommon parameters:")
        print(f"--listen                 # Allow external connections")
        print(f"--api-port {api_port}     # API server port")
        print(f"--api                    # Enable API mode")
        print(f"--model MODEL_NAME       # Load specific model")
        print(f"--chat                   # Enable chat interface")
        print(f"--notebook               # Enable notebook interface")
        
        print(f"\nOnce running:")
        print(f"• Web interface: http://{host}:{port}")
        print(f"• API endpoint: http://{host}:{api_port}")
        
        return True
    
    def troubleshoot_connection(self, base_url: str) -> List[str]:
        """Provide troubleshooting steps for connection issues."""
        issues = []
        
        # Check basic connectivity
        try:
            response = requests.get(base_url, timeout=5)
            if response.status_code != 200:
                issues.append(f"Server responds with status {response.status_code} (expected 200)")
        except requests.exceptions.ConnectionError:
            issues.append("Cannot connect to server - check if Text-Generation-WebUI is running")
        except requests.exceptions.Timeout:
            issues.append("Connection timeout - server may be starting up")
        
        # Check API endpoints
        api_working = False
        for endpoint in self.api_endpoints:
            try:
                url = f"{base_url}{endpoint}"
                response = requests.get(url, timeout=5)
                if response.status_code == 200:
                    api_working = True
                    break
            except:
                continue
        
        if not api_working:
            issues.append("API endpoints not responding - ensure --api flag is used when starting server")
        
        # Add general advice
        issues.extend([
            "Make sure Text-Generation-WebUI is started with --api flag",
            "Check that a model is loaded in the WebUI",
            "Verify the correct API port is being used (default: 5000)",
            "Ensure firewall isn't blocking the connection",
            "Check if the server is listening on the correct host (use --listen for external access)"
        ])
        
        return issues
    
    def detect_models(self, base_url: str) -> List[str]:
        """Detect available models from WebUI."""
        models = []
        
        try:
            endpoints_to_test = [
                f"{base_url}/v1/models",
                f"{base_url}/api/v1/models",
                f"{base_url}/models"
            ]
            
            for endpoint in endpoints_to_test:
                try:
                    response = requests.get(endpoint, timeout=10)
                    if response.status_code == 200:
                        data = response.json()
                        
                        if isinstance(data, dict) and "data" in data:
                            models = [model.get("id", model.get("model", "unknown")) for model in data["data"]]
                        elif isinstance(data, list):
                            models = [model.get("id", model.get("model", "unknown")) for model in data]
                        
                        if models:
                            break
                            
                except:
                    continue
                    
        except Exception as e:
            print(f"Error detecting models: {e}")
        
        return models
    
    def run_diagnostic(self) -> bool:
        """Run complete Text-Generation-WebUI diagnostic."""
        print("🔍 Text-Generation-WebUI Diagnostic Tool")
        print("=" * 50)
        
        # Check installation
        print("\n1. Checking Text-Generation-WebUI installation...")
        installed, info = self.check_webui_installation()
        if installed:
            print(f"✅ {info}")
        else:
            print(f"❌ {info}")
            print("\nInstallation options:")
            self.install_webui()
            return False
        
        # Check running server
        print("\n2. Checking for running Text-Generation-WebUI...")
        running, info, url = self.check_webui_running()
        if running:
            print(f"✅ {info}")
            
            # Test API
            print("\n3. Testing Text-Generation-WebUI API...")
            api_works, api_info = self.test_webui_api(url)
            if api_works:
                print(f"✅ {api_info}")
                
                # Detect models
                print("\n4. Detecting available models...")
                models = self.detect_models(url)
                if models:
                    print(f"✅ Found {len(models)} models: {', '.join(models[:5])}")
                    if len(models) > 5:
                        print(f"   ... and {len(models) - 5} more")
                else:
                    print("⚠️  No models detected - make sure a model is loaded in WebUI")
                
                # Generate configuration
                print(f"\n5. Configuration for AI Utilities:")
                config = self.generate_env_config(url)
                print(config)
                
                return True
            else:
                print(f"❌ {api_info}")
                print("\nTroubleshooting suggestions:")
                for issue in self.troubleshoot_connection(url):
                    print(f"• {issue}")
                return False
        else:
            print(f"❌ {info}")
            print("\nTo start Text-Generation-WebUI:")
            self.start_webui_server()
            return False
    
    def interactive_setup(self) -> bool:
        """Interactive setup wizard."""
        print("🧙 Text-Generation-WebUI Interactive Setup")
        print("=" * 45)
        
        # Check installation
        installed, info = self.check_webui_installation()
        if not installed:
            print(f"❌ {info}")
            install = input("Get installation instructions? (y/n): ").lower().strip()
            if install == 'y':
                self.install_webui()
            return False
        
        # Find running server
        print("\n🔍 Looking for Text-Generation-WebUI...")
        running, info, url = self.check_webui_running()
        
        if not running:
            print("❌ No running Text-Generation-WebUI found")
            print("\nOptions:")
            print("1. Get startup instructions")
            print("2. Enter server URL manually")
            print("3. Exit")
            
            choice = input("Choose option (1/2/3): ").strip()
            
            if choice == "1":
                self.start_webui_server()
                input("\nPress Enter after starting Text-Generation-WebUI...")
                
                # Check again
                running, info, url = self.check_webui_running()
                if not running:
                    print("❌ Still cannot find Text-Generation-WebUI")
                    return False
                    
            elif choice == "2":
                url = input("Enter WebUI server URL (e.g., http://127.0.0.1:5000): ").strip()
                if not url.startswith('http'):
                    url = f"http://{url}"
                    
            elif choice == "3":
                return False
            else:
                print("Invalid choice")
                return False
        
        # Test the connection
        print(f"\n🧪 Testing connection to {url}")
        api_works, api_info = self.test_webui_api(url)
        
        if api_works:
            print(f"✅ {api_info}")
            
            # Detect models
            models = self.detect_models(url)
            if models:
                print(f"\n📋 Available models:")
                for i, model in enumerate(models[:10], 1):
                    print(f"   {i}. {model}")
                if len(models) > 10:
                    print(f"   ... and {len(models) - 10} more")
                
                # Let user choose model
                model_choice = input(f"\nEnter model name or press Enter for default: ").strip()
                if model_choice and model_choice in models:
                    print(f"✅ Selected model: {model_choice}")
                else:
                    model_choice = models[0] if models else "local-model"
                    print(f"Using default model: {model_choice}")
            else:
                model_choice = "local-model"
                print("⚠️  No models detected - using default")
            
            # Save configuration
            save_config = input("\nSave configuration to .env file? (y/n): ").lower().strip()
            if save_config == 'y':
                config = self.generate_env_config(url)
                # Update config with selected model
                config = config.replace("AI_MODEL=local-model", f"AI_MODEL={model_choice}")
                
                env_file = Path(".env")
                
                if env_file.exists():
                    backup_content = env_file.read_text()
                    env_file.write_text(f"{backup_content}\n{config}")
                else:
                    env_file.write_text(config)
                
                print(f"✅ Configuration saved to {env_file}")
            
            print(f"\n🎉 Text-Generation-WebUI setup complete!")
            print(f"You can now use AI Utilities with Text-Generation-WebUI provider")
            return True
        else:
            print(f"❌ {api_info}")
            print("\nTroubleshooting:")
            for issue in self.troubleshoot_connection(url):
                print(f"• {issue}")
            return False
    
    def generate_test_script(self, base_url: str, model: str) -> str:
        """Generate a test script for the WebUI configuration."""
        script = f'''#!/usr/bin/env python3
"""Test script for Text-Generation-WebUI configuration."""

import os
from ai_utilities import create_client

def test_webui():
    """Test Text-Generation-WebUI connection."""
    
    # Configuration
    os.environ["AI_PROVIDER"] = "openai_compatible"
    os.environ["AI_BASE_URL"] = "{base_url}/v1"
    os.environ["AI_API_KEY"] = "not-required"
    os.environ["AI_MODEL"] = "{model}"
    
    try:
        # Create client
        client = create_client()
        
        # Test basic request
        response = client.ask("Hello! This is a test message.")
        print(f"✅ Test successful!")
        print(f"Response: {{response[:100]}}...")
        
        return True
        
    except Exception as e:
        print(f"❌ Test failed: {{e}}")
        return False

if __name__ == "__main__":
    test_webui()
'''
        return script


def main():
    """Main entry point for Text-Generation-WebUI setup helper."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Text-Generation-WebUI setup and diagnostic tool")
    parser.add_argument("--diagnostic", action="store_true", 
                       help="Run diagnostic only")
    parser.add_argument("--interactive", action="store_true",
                       help="Run interactive setup wizard")
    parser.add_argument("--check", action="store_true",
                       help="Check if WebUI is running")
    parser.add_argument("--url", type=str,
                       help="Test specific WebUI URL")
    parser.add_argument("--install-guide", action="store_true",
                       help="Show installation guide")
    parser.add_argument("--start-guide", action="store_true",
                       help="Show startup guide")
    
    args = parser.parse_args()
    
    helper = TextGenerationWebUISetupHelper()
    
    if args.interactive:
        success = helper.interactive_setup()
    elif args.diagnostic:
        success = helper.run_diagnostic()
    elif args.check:
        running, info, url = helper.check_webui_running()
        if running:
            print(f"✅ {info}")
            success = True
        else:
            print(f"❌ {info}")
            success = False
    elif args.url:
        api_works, api_info = helper.test_webui_api(args.url)
        if api_works:
            print(f"✅ {api_info}")
            success = True
        else:
            print(f"❌ {api_info}")
            success = False
    elif args.install_guide:
        success = helper.install_webui()
    elif args.start_guide:
        success = helper.start_webui_server()
    else:
        # Default: run diagnostic
        success = helper.run_diagnostic()
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()